// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalItlock.Web.Data;

#nullable disable

namespace PortalItlock.Web.Migrations.Platform
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261007122254_LeggTilTenantOrganisasjonsfelterOgLisenser")]
    partial class LeggTilTenantOrganisasjonsfelterOgLisenser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PortalItlock.Web.Models.PlattformBruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlattformBrukere");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PlattformBrukerPasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Brukt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlattformBrukerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtlopsDato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlattformBrukerId");

                    b.ToTable("PlattformBrukerPasswordResetTokener");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epost")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErStandard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kundeansvarlig")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgNr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postnr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SistOppdatert")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subdomene")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.TenantLisens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntallTildelt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantLisenser");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PlattformBrukerPasswordResetToken", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.PlattformBruker", "PlattformBruker")
                        .WithMany()
                        .HasForeignKey("PlattformBrukerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlattformBruker");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.TenantLisens", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Tenant", "Tenant")
                        .WithMany("Lisenser")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Tenant", b =>
                {
                    b.Navigation("Lisenser");
                });
#pragma warning restore 612, 618
        }
    }
}
