// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalItlock.Web.Data;

#nullable disable

namespace PortalItlock.Web.Migrations.Platform
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261001090207_LeggTilPlattformBruker")]
    partial class LeggTilPlattformBruker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PortalItlock.Web.Models.PlattformBruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlattformBrukere");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PlattformBrukerPasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Brukt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlattformBrukerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtlopsDato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlattformBrukerId");

                    b.ToTable("PlattformBrukerPasswordResetTokener");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErStandard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subdomene")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PlattformBrukerPasswordResetToken", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.PlattformBruker", "PlattformBruker")
                        .WithMany()
                        .HasForeignKey("PlattformBrukerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlattformBruker");
                });
#pragma warning restore 612, 618
        }
    }
}
