// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalItlock.Web.Data;

#nullable disable

namespace PortalItlock.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814125824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Produktkode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produsent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErManuell")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpprettetAv")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageComponent", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antall")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("PackageComponents");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageRequirement", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementValueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "RequirementValueId");

                    b.HasIndex("RequirementValueId");

                    b.ToTable("PackageRequirements");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RequirementDimensions");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementDimensionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDimensionId");

                    b.ToTable("RequirementValues");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.ComponentType", "Type")
                        .WithMany("Komponenter")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageComponent", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Component", "Component")
                        .WithMany("Pakker")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalItlock.Web.Models.Package", "Package")
                        .WithMany("Komponenter")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageRequirement", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Package", "Package")
                        .WithMany("Krav")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalItlock.Web.Models.RequirementValue", "RequirementValue")
                        .WithMany("Pakker")
                        .HasForeignKey("RequirementValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("RequirementValue");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.RequirementDimension", "Dimensjon")
                        .WithMany("Verdier")
                        .HasForeignKey("RequirementDimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensjon");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.Navigation("Pakker");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.ComponentType", b =>
                {
                    b.Navigation("Komponenter");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Package", b =>
                {
                    b.Navigation("Komponenter");

                    b.Navigation("Krav");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementDimension", b =>
                {
                    b.Navigation("Verdier");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.Navigation("Pakker");
                });
#pragma warning restore 612, 618
        }
    }
}
