// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalItlock.Web.Data;

#nullable disable

namespace PortalItlock.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816153114_LasUtskiftingModel")]
    partial class LasUtskiftingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PortalItlock.Web.Models.Befaring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("BefartAv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bygg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Epost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kontaktperson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kundenavn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kundenr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oppdrag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postnr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemNr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tlf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Befaringer");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.BefaringDorfelt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adapter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Albuekontakter")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnetUtstyrDorlukker")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnetUtstyrOvrig")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApnekraftMaks30N")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmGlideskinne")
                        .HasColumnType("TEXT");

                    b.Property<string>("Automatikk")
                        .HasColumnType("TEXT");

                    b.Property<int>("BefaringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrakettMl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brannklasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brannkrav")
                        .HasColumnType("TEXT");

                    b.Property<string>("BxH")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dorlukker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dornavn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dornr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dortype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Floyer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Handtak")
                        .HasColumnType("TEXT");

                    b.Property<string>("KabelAutomatikk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lassystemnr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Magnetlas")
                        .HasColumnType("TEXT");

                    b.Property<string>("MontasjeSideAutomatikk")
                        .HasColumnType("TEXT");

                    b.Property<string>("MontasjeSideDorlukker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notater")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panikkbeslag")
                        .HasColumnType("TEXT");

                    b.Property<string>("RadarSensor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Risikoklasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sikkerhetssensor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sikringsklasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slagretning")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrekkSkyvArm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversellUtforming")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpsNodstrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("VkPlate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BefaringId");

                    b.ToTable("BefaringDorfelt");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.BefaringLassystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnnetUtstyr")
                        .HasColumnType("TEXT");

                    b.Property<int>("BefaringDorfeltId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DortykkelseAB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dorvrider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElSluttstykke")
                        .HasColumnType("TEXT");

                    b.Property<string>("Festelepper")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Karmoverforing")
                        .HasColumnType("TEXT");

                    b.Property<string>("Laskasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Magnetkontakt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MekSluttstykke")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mikrobryter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nodutstyr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overflate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skilt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stolpe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sylinder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Volt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BefaringDorfeltId");

                    b.ToTable("BefaringLassystemer");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Leverandor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrisNetto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrisVeiledende")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produktkode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produsent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Varegruppe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Navn = "Låskasse 1"
                        },
                        new
                        {
                            Id = 2,
                            Navn = "Sluttstykke 1"
                        },
                        new
                        {
                            Id = 3,
                            Navn = "Stolpe 1"
                        },
                        new
                        {
                            Id = 4,
                            Navn = "Sylinder 1 utv"
                        },
                        new
                        {
                            Id = 5,
                            Navn = "Sylinder 1 innv."
                        },
                        new
                        {
                            Id = 6,
                            Navn = "Sylinder utstyr"
                        },
                        new
                        {
                            Id = 7,
                            Navn = "Sylinder utstyr 2"
                        },
                        new
                        {
                            Id = 8,
                            Navn = "Sylinder utstyr 3"
                        },
                        new
                        {
                            Id = 9,
                            Navn = "Håndtak"
                        },
                        new
                        {
                            Id = 10,
                            Navn = "Dørvrider"
                        },
                        new
                        {
                            Id = 11,
                            Navn = "Skilt 1"
                        },
                        new
                        {
                            Id = 12,
                            Navn = "Låskasse 2"
                        },
                        new
                        {
                            Id = 13,
                            Navn = "Sluttstykke 2"
                        },
                        new
                        {
                            Id = 14,
                            Navn = "Sluttstykke 2 utstyr"
                        },
                        new
                        {
                            Id = 15,
                            Navn = "Sylinder 2 utv"
                        },
                        new
                        {
                            Id = 16,
                            Navn = "Sylinder 2 innv"
                        },
                        new
                        {
                            Id = 17,
                            Navn = "Sylinder 2 utstyr"
                        },
                        new
                        {
                            Id = 18,
                            Navn = "Sylinder 2 utstyr 2"
                        },
                        new
                        {
                            Id = 19,
                            Navn = "Skilt 2"
                        },
                        new
                        {
                            Id = 20,
                            Navn = "Sylinderskruer"
                        },
                        new
                        {
                            Id = 21,
                            Navn = "Dørautomatikk"
                        },
                        new
                        {
                            Id = 22,
                            Navn = "Dørautomatikk arm/skinne"
                        },
                        new
                        {
                            Id = 23,
                            Navn = "Klemsikring bakkant"
                        },
                        new
                        {
                            Id = 24,
                            Navn = "Klemsikring forkant"
                        },
                        new
                        {
                            Id = 25,
                            Navn = "Kelmsikring karmoverføring"
                        },
                        new
                        {
                            Id = 26,
                            Navn = "Dørautomatikk utstyr"
                        },
                        new
                        {
                            Id = 27,
                            Navn = "Dørautomatikk utstyr 2"
                        },
                        new
                        {
                            Id = 28,
                            Navn = "Dørautomatikk blindplugg"
                        },
                        new
                        {
                            Id = 29,
                            Navn = "Dørautomatikk utstyr 4"
                        },
                        new
                        {
                            Id = 30,
                            Navn = "Dørautomatikk utstyr 5"
                        },
                        new
                        {
                            Id = 31,
                            Navn = "Kortleser inn"
                        },
                        new
                        {
                            Id = 32,
                            Navn = "Kortleser ut"
                        },
                        new
                        {
                            Id = 33,
                            Navn = "Kortleser styreenhet"
                        },
                        new
                        {
                            Id = 34,
                            Navn = "Impulsbryter innv"
                        },
                        new
                        {
                            Id = 35,
                            Navn = "Impulsbryter utv."
                        },
                        new
                        {
                            Id = 36,
                            Navn = "Impulsbryter utstyr"
                        },
                        new
                        {
                            Id = 37,
                            Navn = "Nøkkelbryter"
                        },
                        new
                        {
                            Id = 38,
                            Navn = "Nkl.bryter sylinder"
                        },
                        new
                        {
                            Id = 39,
                            Navn = "Dørlukker aktiv fløy"
                        },
                        new
                        {
                            Id = 40,
                            Navn = "Dørlukker arm/skinne"
                        },
                        new
                        {
                            Id = 41,
                            Navn = "Dørlukker passiv fløy"
                        },
                        new
                        {
                            Id = 42,
                            Navn = "Dørlukker utstyr"
                        },
                        new
                        {
                            Id = 43,
                            Navn = "Dørlukker utstyr 2"
                        },
                        new
                        {
                            Id = 44,
                            Navn = "Panikkbeslag/Skåte"
                        },
                        new
                        {
                            Id = 45,
                            Navn = "Panikkbeslag utstyr"
                        },
                        new
                        {
                            Id = 46,
                            Navn = "Panikkbeslag utstyr 2"
                        },
                        new
                        {
                            Id = 47,
                            Navn = "Panikkbeslag utstyr 3"
                        },
                        new
                        {
                            Id = 48,
                            Navn = "Panikkbeslag utstyr 4"
                        },
                        new
                        {
                            Id = 49,
                            Navn = "Panikkbeslag utstyr 5"
                        },
                        new
                        {
                            Id = 50,
                            Navn = "Magnetlås passiv fløy"
                        },
                        new
                        {
                            Id = 51,
                            Navn = "Magnetlås utstyr"
                        },
                        new
                        {
                            Id = 52,
                            Navn = "Magnetlås utstyr 2"
                        },
                        new
                        {
                            Id = 53,
                            Navn = "Nødutstyr mekanisk"
                        },
                        new
                        {
                            Id = 54,
                            Navn = "Nødutstyr elektrisk"
                        },
                        new
                        {
                            Id = 55,
                            Navn = "Karmoverføring aktiv fløy"
                        },
                        new
                        {
                            Id = 56,
                            Navn = "Karmoverføring passiv fløy"
                        },
                        new
                        {
                            Id = 57,
                            Navn = "Kabel"
                        },
                        new
                        {
                            Id = 58,
                            Navn = "Dørstopper"
                        },
                        new
                        {
                            Id = 59,
                            Navn = "Magnetkontakt"
                        },
                        new
                        {
                            Id = 60,
                            Navn = "Grensesnittboks"
                        },
                        new
                        {
                            Id = 61,
                            Navn = "Grensesnittboks utstyr 1"
                        },
                        new
                        {
                            Id = 62,
                            Navn = "Grensesnittboks utstyr 2"
                        },
                        new
                        {
                            Id = 63,
                            Navn = "Diverse 1"
                        },
                        new
                        {
                            Id = 64,
                            Navn = "Diverse 2"
                        },
                        new
                        {
                            Id = 65,
                            Navn = "Diverse 3"
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.DoorEnvironmentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DoorEnvironmentDocuments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "dormiljo-1.pdf",
                            Navn = "Dørmiljø 1",
                            Rekkefolge = 1
                        },
                        new
                        {
                            Id = 2,
                            FileName = "dormiljo-2.pdf",
                            Navn = "Dørmiljø 2",
                            Rekkefolge = 2
                        },
                        new
                        {
                            Id = 3,
                            FileName = "dormiljo-3.pdf",
                            Navn = "Dørmiljø 3",
                            Rekkefolge = 3
                        },
                        new
                        {
                            Id = 4,
                            FileName = "dormiljo-4.pdf",
                            Navn = "Dørmiljø 4",
                            Rekkefolge = 4
                        },
                        new
                        {
                            Id = 5,
                            FileName = "dormiljo-5.pdf",
                            Navn = "Dørmiljø 5",
                            Rekkefolge = 5
                        },
                        new
                        {
                            Id = 6,
                            FileName = "dormiljo-6.pdf",
                            Navn = "Dørmiljø 6",
                            Rekkefolge = 6
                        },
                        new
                        {
                            Id = 7,
                            FileName = "dormiljo-7.pdf",
                            Navn = "Dørmiljø 7",
                            Rekkefolge = 7
                        },
                        new
                        {
                            Id = 8,
                            FileName = "dormiljo-8.pdf",
                            Navn = "Dørmiljø 8",
                            Rekkefolge = 8
                        },
                        new
                        {
                            Id = 9,
                            FileName = "dormiljo-9.pdf",
                            Navn = "Dørmiljø 9",
                            Rekkefolge = 9
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.LasUtskifting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvstandDorkantTilSkiltMm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("DorFabrikat")
                        .HasColumnType("TEXT");

                    b.Property<string>("DorNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("HengslingSide")
                        .HasColumnType("TEXT");

                    b.Property<string>("InnsideMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("KarmAvstand")
                        .HasColumnType("TEXT");

                    b.Property<string>("KarmFabrikat")
                        .HasColumnType("TEXT");

                    b.Property<string>("KarmNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merknad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overflatebehandling")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverflatebehandlingAnnet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skruer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slagretning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stolpebredde")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stolpehoyde")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UtsideMm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LasUtskiftinger");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErManuell")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpprettetAv")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageComponent", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antall")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("PackageComponents");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageRequirement", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementValueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "RequirementValueId");

                    b.HasIndex("RequirementValueId");

                    b.ToTable("PackageRequirements");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RequirementDimensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Navn = "Type dør",
                            Rekkefolge = 1
                        },
                        new
                        {
                            Id = 2,
                            Navn = "Hvilke bruk",
                            Rekkefolge = 2
                        },
                        new
                        {
                            Id = 3,
                            Navn = "FG",
                            Rekkefolge = 3
                        },
                        new
                        {
                            Id = 4,
                            Navn = "Risikoklasse",
                            Rekkefolge = 4
                        },
                        new
                        {
                            Id = 5,
                            Navn = "Lukkefunksjon",
                            Rekkefolge = 5
                        },
                        new
                        {
                            Id = 6,
                            Navn = "Antall fløyer",
                            Rekkefolge = 6
                        },
                        new
                        {
                            Id = 7,
                            Navn = "Type beslag",
                            Rekkefolge = 7
                        },
                        new
                        {
                            Id = 8,
                            Navn = "Tilbakerømning",
                            Rekkefolge = 8
                        },
                        new
                        {
                            Id = 9,
                            Navn = "Postsonesylinder",
                            Rekkefolge = 9
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementDimensionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDimensionId");

                    b.ToTable("RequirementValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rekkefolge = 1,
                            RequirementDimensionId = 1,
                            Verdi = "Innerdør"
                        },
                        new
                        {
                            Id = 2,
                            Rekkefolge = 2,
                            RequirementDimensionId = 1,
                            Verdi = "Ytterdør"
                        },
                        new
                        {
                            Id = 3,
                            Rekkefolge = 1,
                            RequirementDimensionId = 2,
                            Verdi = "Låsbar"
                        },
                        new
                        {
                            Id = 4,
                            Rekkefolge = 2,
                            RequirementDimensionId = 2,
                            Verdi = "Ikke låsbar"
                        },
                        new
                        {
                            Id = 5,
                            Rekkefolge = 3,
                            RequirementDimensionId = 2,
                            Verdi = "Toalett"
                        },
                        new
                        {
                            Id = 6,
                            Rekkefolge = 4,
                            RequirementDimensionId = 2,
                            Verdi = "Forberedt for kortleser"
                        },
                        new
                        {
                            Id = 7,
                            Rekkefolge = 5,
                            RequirementDimensionId = 2,
                            Verdi = "Med kortleser"
                        },
                        new
                        {
                            Id = 8,
                            Rekkefolge = 6,
                            RequirementDimensionId = 2,
                            Verdi = "Med dørbladmontert kortleser"
                        },
                        new
                        {
                            Id = 9,
                            Rekkefolge = 7,
                            RequirementDimensionId = 2,
                            Verdi = "Kun rømning RK 1-4"
                        },
                        new
                        {
                            Id = 10,
                            Rekkefolge = 8,
                            RequirementDimensionId = 2,
                            Verdi = "Kun rømning RK 1-6"
                        },
                        new
                        {
                            Id = 11,
                            Rekkefolge = 1,
                            RequirementDimensionId = 3,
                            Verdi = "Ikke FG"
                        },
                        new
                        {
                            Id = 12,
                            Rekkefolge = 2,
                            RequirementDimensionId = 3,
                            Verdi = "FG"
                        },
                        new
                        {
                            Id = 13,
                            Rekkefolge = 1,
                            RequirementDimensionId = 4,
                            Verdi = "Ikke rømning"
                        },
                        new
                        {
                            Id = 14,
                            Rekkefolge = 2,
                            RequirementDimensionId = 4,
                            Verdi = "1-4"
                        },
                        new
                        {
                            Id = 15,
                            Rekkefolge = 3,
                            RequirementDimensionId = 4,
                            Verdi = "1-6"
                        },
                        new
                        {
                            Id = 16,
                            Rekkefolge = 1,
                            RequirementDimensionId = 5,
                            Verdi = "Ingen lukker"
                        },
                        new
                        {
                            Id = 17,
                            Rekkefolge = 2,
                            RequirementDimensionId = 5,
                            Verdi = "Dørlukker"
                        },
                        new
                        {
                            Id = 18,
                            Rekkefolge = 3,
                            RequirementDimensionId = 5,
                            Verdi = "Automatikk"
                        },
                        new
                        {
                            Id = 19,
                            Rekkefolge = 4,
                            RequirementDimensionId = 5,
                            Verdi = "Dørlukker/automatikk"
                        },
                        new
                        {
                            Id = 20,
                            Rekkefolge = 1,
                            RequirementDimensionId = 6,
                            Verdi = "1-fløyet"
                        },
                        new
                        {
                            Id = 21,
                            Rekkefolge = 2,
                            RequirementDimensionId = 6,
                            Verdi = "2-fløyet"
                        },
                        new
                        {
                            Id = 22,
                            Rekkefolge = 3,
                            RequirementDimensionId = 6,
                            Verdi = "Skyvedør"
                        },
                        new
                        {
                            Id = 23,
                            Rekkefolge = 1,
                            RequirementDimensionId = 7,
                            Verdi = "Mekanisk"
                        },
                        new
                        {
                            Id = 24,
                            Rekkefolge = 2,
                            RequirementDimensionId = 7,
                            Verdi = "Elektrisk"
                        },
                        new
                        {
                            Id = 25,
                            Rekkefolge = 3,
                            RequirementDimensionId = 7,
                            Verdi = "Lukket/låst signal"
                        },
                        new
                        {
                            Id = 26,
                            Rekkefolge = 4,
                            RequirementDimensionId = 7,
                            Verdi = "Hengelås"
                        },
                        new
                        {
                            Id = 27,
                            Rekkefolge = 1,
                            RequirementDimensionId = 8,
                            Verdi = "Nei"
                        },
                        new
                        {
                            Id = 28,
                            Rekkefolge = 2,
                            RequirementDimensionId = 8,
                            Verdi = "Ja"
                        },
                        new
                        {
                            Id = 29,
                            Rekkefolge = 3,
                            RequirementDimensionId = 8,
                            Verdi = "Ikke aktuelt"
                        },
                        new
                        {
                            Id = 30,
                            Rekkefolge = 1,
                            RequirementDimensionId = 9,
                            Verdi = "Nei"
                        },
                        new
                        {
                            Id = 31,
                            Rekkefolge = 2,
                            RequirementDimensionId = 9,
                            Verdi = "Ja"
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.BefaringDorfelt", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Befaring", "Befaring")
                        .WithMany("Dorfelt")
                        .HasForeignKey("BefaringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Befaring");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.BefaringLassystem", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.BefaringDorfelt", "Dorfelt")
                        .WithMany("Lassystemer")
                        .HasForeignKey("BefaringDorfeltId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dorfelt");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.ComponentType", "Type")
                        .WithMany("Komponenter")
                        .HasForeignKey("ComponentTypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageComponent", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Component", "Component")
                        .WithMany("Pakker")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalItlock.Web.Models.Package", "Package")
                        .WithMany("Komponenter")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageRequirement", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Package", "Package")
                        .WithMany("Krav")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalItlock.Web.Models.RequirementValue", "RequirementValue")
                        .WithMany("Pakker")
                        .HasForeignKey("RequirementValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("RequirementValue");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.RequirementDimension", "Dimensjon")
                        .WithMany("Verdier")
                        .HasForeignKey("RequirementDimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensjon");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Befaring", b =>
                {
                    b.Navigation("Dorfelt");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.BefaringDorfelt", b =>
                {
                    b.Navigation("Lassystemer");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.Navigation("Pakker");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.ComponentType", b =>
                {
                    b.Navigation("Komponenter");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Package", b =>
                {
                    b.Navigation("Komponenter");

                    b.Navigation("Krav");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementDimension", b =>
                {
                    b.Navigation("Verdier");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.Navigation("Pakker");
                });
#pragma warning restore 612, 618
        }
    }
}
