// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalItlock.Web.Data;

#nullable disable

namespace PortalItlock.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814132412_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Produktkode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produsent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Navn = "Dørblad"
                        },
                        new
                        {
                            Id = 2,
                            Navn = "Karm"
                        },
                        new
                        {
                            Id = 3,
                            Navn = "Hengsler"
                        },
                        new
                        {
                            Id = 4,
                            Navn = "Terskel"
                        },
                        new
                        {
                            Id = 5,
                            Navn = "Låskasse"
                        },
                        new
                        {
                            Id = 6,
                            Navn = "Sluttstykke"
                        },
                        new
                        {
                            Id = 7,
                            Navn = "Dørvrider"
                        },
                        new
                        {
                            Id = 8,
                            Navn = "Sylinder/lås"
                        },
                        new
                        {
                            Id = 9,
                            Navn = "Panikkbeslag"
                        },
                        new
                        {
                            Id = 10,
                            Navn = "Dørpumpe"
                        },
                        new
                        {
                            Id = 11,
                            Navn = "Dørautomatikk"
                        },
                        new
                        {
                            Id = 12,
                            Navn = "Koordinering"
                        },
                        new
                        {
                            Id = 13,
                            Navn = "Kortleser"
                        },
                        new
                        {
                            Id = 14,
                            Navn = "Albuebryter"
                        },
                        new
                        {
                            Id = 15,
                            Navn = "Utspaseringsknapp"
                        },
                        new
                        {
                            Id = 16,
                            Navn = "Koblingsboks"
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErManuell")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpprettetAv")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageComponent", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antall")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("PackageComponents");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageRequirement", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementValueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "RequirementValueId");

                    b.HasIndex("RequirementValueId");

                    b.ToTable("PackageRequirements");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RequirementDimensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Navn = "Dørtype",
                            Rekkefolge = 1
                        },
                        new
                        {
                            Id = 2,
                            Navn = "Brannklasse",
                            Rekkefolge = 2
                        },
                        new
                        {
                            Id = 3,
                            Navn = "Risikoklasse",
                            Rekkefolge = 3
                        },
                        new
                        {
                            Id = 4,
                            Navn = "Rømningskrav",
                            Rekkefolge = 4
                        },
                        new
                        {
                            Id = 5,
                            Navn = "Sikkerhetsklasse",
                            Rekkefolge = 5
                        },
                        new
                        {
                            Id = 6,
                            Navn = "Automatisk døråpner",
                            Rekkefolge = 6
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementDimensionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDimensionId");

                    b.ToTable("RequirementValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rekkefolge = 1,
                            RequirementDimensionId = 1,
                            Verdi = "Innerdør"
                        },
                        new
                        {
                            Id = 2,
                            Rekkefolge = 2,
                            RequirementDimensionId = 1,
                            Verdi = "Ytterdør"
                        },
                        new
                        {
                            Id = 3,
                            Rekkefolge = 3,
                            RequirementDimensionId = 1,
                            Verdi = "Branndør"
                        },
                        new
                        {
                            Id = 4,
                            Rekkefolge = 1,
                            RequirementDimensionId = 2,
                            Verdi = "Ingen"
                        },
                        new
                        {
                            Id = 5,
                            Rekkefolge = 2,
                            RequirementDimensionId = 2,
                            Verdi = "EI30"
                        },
                        new
                        {
                            Id = 6,
                            Rekkefolge = 3,
                            RequirementDimensionId = 2,
                            Verdi = "EI60"
                        },
                        new
                        {
                            Id = 7,
                            Rekkefolge = 1,
                            RequirementDimensionId = 3,
                            Verdi = "RKL1"
                        },
                        new
                        {
                            Id = 8,
                            Rekkefolge = 2,
                            RequirementDimensionId = 3,
                            Verdi = "RKL2"
                        },
                        new
                        {
                            Id = 9,
                            Rekkefolge = 3,
                            RequirementDimensionId = 3,
                            Verdi = "RKL3"
                        },
                        new
                        {
                            Id = 10,
                            Rekkefolge = 4,
                            RequirementDimensionId = 3,
                            Verdi = "RKL4"
                        },
                        new
                        {
                            Id = 11,
                            Rekkefolge = 5,
                            RequirementDimensionId = 3,
                            Verdi = "RKL5"
                        },
                        new
                        {
                            Id = 12,
                            Rekkefolge = 6,
                            RequirementDimensionId = 3,
                            Verdi = "RKL6"
                        },
                        new
                        {
                            Id = 13,
                            Rekkefolge = 1,
                            RequirementDimensionId = 4,
                            Verdi = "Rømning"
                        },
                        new
                        {
                            Id = 14,
                            Rekkefolge = 2,
                            RequirementDimensionId = 4,
                            Verdi = "Ikke rømning"
                        },
                        new
                        {
                            Id = 15,
                            Rekkefolge = 3,
                            RequirementDimensionId = 4,
                            Verdi = "Tilbakerømning"
                        },
                        new
                        {
                            Id = 16,
                            Rekkefolge = 1,
                            RequirementDimensionId = 5,
                            Verdi = "RC1"
                        },
                        new
                        {
                            Id = 17,
                            Rekkefolge = 2,
                            RequirementDimensionId = 5,
                            Verdi = "RC2"
                        },
                        new
                        {
                            Id = 18,
                            Rekkefolge = 3,
                            RequirementDimensionId = 5,
                            Verdi = "RC3"
                        },
                        new
                        {
                            Id = 19,
                            Rekkefolge = 4,
                            RequirementDimensionId = 5,
                            Verdi = "RC4"
                        },
                        new
                        {
                            Id = 20,
                            Rekkefolge = 5,
                            RequirementDimensionId = 5,
                            Verdi = "RC5"
                        },
                        new
                        {
                            Id = 21,
                            Rekkefolge = 1,
                            RequirementDimensionId = 6,
                            Verdi = "Ja"
                        },
                        new
                        {
                            Id = 22,
                            Rekkefolge = 2,
                            RequirementDimensionId = 6,
                            Verdi = "Nei"
                        });
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.ComponentType", "Type")
                        .WithMany("Komponenter")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageComponent", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Component", "Component")
                        .WithMany("Pakker")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalItlock.Web.Models.Package", "Package")
                        .WithMany("Komponenter")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.PackageRequirement", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.Package", "Package")
                        .WithMany("Krav")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalItlock.Web.Models.RequirementValue", "RequirementValue")
                        .WithMany("Pakker")
                        .HasForeignKey("RequirementValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("RequirementValue");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.HasOne("PortalItlock.Web.Models.RequirementDimension", "Dimensjon")
                        .WithMany("Verdier")
                        .HasForeignKey("RequirementDimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensjon");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Component", b =>
                {
                    b.Navigation("Pakker");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.ComponentType", b =>
                {
                    b.Navigation("Komponenter");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.Package", b =>
                {
                    b.Navigation("Komponenter");

                    b.Navigation("Krav");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementDimension", b =>
                {
                    b.Navigation("Verdier");
                });

            modelBuilder.Entity("PortalItlock.Web.Models.RequirementValue", b =>
                {
                    b.Navigation("Pakker");
                });
#pragma warning restore 612, 618
        }
    }
}
